# Table of Contents

## 1. Importing Libraries
## 2. Importing Data
## 3. Creating Price Labels and Busiest Days Columns
### 3.1 Sorting Products into Price Ranges
### 3.2 Creating "busiest_day" column
### 3.3 Change “Busiest day” to become “Busiest days”
### 3.4 Create Slowest Days Column
## 4. Identify Busiest Hour of Day
## 5. Exporting Data

# 1. Importing Libraries

In [99]:
# Import Libraries
import pandas as pd
import numpy as np
import os

# 2. Importing Data

In [101]:
# Import ords_prods_deps_cleaned.pkl
ords_prods_deps_cleaned = pd.read_pickle(r'/Users/xxx/Documents/Instacart Basket Analysis - 2025-01-05/02 - Data/Prepared Data/ords_prods_deps_cleaned.pkl')

# 3. Creating the “price_label” and “busiest_day” columns

## 3.1 Sorting products into price ranges

In [155]:
# If the item’s price is lower than or equal to $5, it will be labeled a “low-range product.”
# If the item’s price is above $5 but lower than or equal to $15, it will be labeled a “mid-range product.”
# If the item’s price is above $15, it will be labeled a “high-range product.”

In [103]:
# subset should include everything from the beginning up to one million rows in the dataframe

df = ords_prods_deps_cleaned[:1000000]

In [105]:
df.shape

(1000000, 15)

In [107]:
# Apply the conditions to create the 'price_range' column
ords_prods_deps_cleaned['price_range'] = pd.cut(
    ords_prods_deps_cleaned['prices'],
    bins=[-float('inf'), 5, 15, float('inf')],  # Define the category cutoffs
    labels=['Low-range product', 'Mid-range product', 'High-range product']
)

# Display the first few rows to check the new column
print(ords_prods_deps_cleaned[['prices', 'price_range']].head())

   prices        price_range
0     9.0  Mid-range product
1    12.5  Mid-range product
2     4.4  Low-range product
3     4.7  Low-range product
4     1.0  Low-range product

In [115]:
#Frequency in %
price_range_percentages = ords_prods_deps_cleaned['price_range'].value_counts(normalize=True) * 100
print(price_range_percentages)

price_range
Mid-range product     67.490914
Low-range product     31.221304
High-range product     1.287782
Name: proportion, dtype: float64

In [36]:
# Define a function
# If the item’s price is lower than or equal to $5, it will be labeled a “low-range product.”
# If the item’s price is above $5 but lower than or equal to $15, it will be labeled a “mid-range product.”
# If the item’s price is above $15, it will be labeled a “high-range product.”

#def price_label(row):

#  if row['prices'] <= 5:
#    return 'Low-range product'
#  elif (row['prices'] > 5) and (row['prices'] <= 15):
#    return 'Mid-range product'
#  elif row['prices'] > 15:
#    return 'High range'
# else: return 'Not enough data'

In [38]:
# Apply the function

# df['price_range'] = df.apply(price_label, axis=1)

In [40]:
# Counting the values in each price category

# df['price_range'].value_counts(dropna = False)

In [42]:
# df['prices'].max()

In [44]:
# df['prices'].min()

In [46]:
# Defining Conditions with loc() function

# df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
# df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product' 
# df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [48]:
# Initialize the 'price_range_loc' column to avoid SettingWithCopyWarning
# df['price_range_loc'] = 'Uncategorized'

# Assign values based on conditions
# df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
# df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'
# df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [50]:
# Ensure df is a deep copy if it was derived from another DataFrame
# df = df.copy(deep=True)

# Initialize the 'price_range_loc' column
# df['price_range_loc'] = 'Uncategorized'

# Assign values based on conditions
# df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
# df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'
# df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [52]:
# Counting the values in each price category

# df['price_range'].value_counts(dropna = False)

In [54]:
# Display data frame

ords_prods_deps_cleaned

,order_id,user_id,order_number,order_weekday,order_hour,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,final_merge_indicator,price_range
0,2539329,1,1,2,8,0,196,1,0,Soda,77,7,9.0,beverages,both,Mid-range product
1,2539329,1,1,2,8,0,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,dairy eggs,both,Mid-range product
2,2539329,1,1,2,8,0,12427,3,0,Original Beef Jerky,23,19,4.4,snacks,both,Low-range product
3,2539329,1,1,2,8,0,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,snacks,both,Low-range product
4,2539329,1,1,2,8,0,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,household,both,Low-range product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,2977660,206209,13,1,12,7,14197,5,1,Tomato Paste,9,9,5.6,dry goods pasta,both,Mid-range product
32434208,2977660,206209,13,1,12,7,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,snacks,both,Mid-range product
32434209,2977660,206209,13,1,12,7,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,snacks,both,Low-range product
32434210,2977660,206209,13,1,12,7,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,snacks,both,Low-range product
32434211,2977660,206209,13,1,12,7,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,snacks,both,Low-range product

## 3.2 Creating "busiest_day" column

In [56]:
# Display data frame

ords_prods_deps_cleaned

,order_id,user_id,order_number,order_weekday,order_hour,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,final_merge_indicator,price_range
0,2539329,1,1,2,8,0,196,1,0,Soda,77,7,9.0,beverages,both,Mid-range product
1,2539329,1,1,2,8,0,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,dairy eggs,both,Mid-range product
2,2539329,1,1,2,8,0,12427,3,0,Original Beef Jerky,23,19,4.4,snacks,both,Low-range product
3,2539329,1,1,2,8,0,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,snacks,both,Low-range product
4,2539329,1,1,2,8,0,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,household,both,Low-range product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,2977660,206209,13,1,12,7,14197,5,1,Tomato Paste,9,9,5.6,dry goods pasta,both,Mid-range product
32434208,2977660,206209,13,1,12,7,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,snacks,both,Mid-range product
32434209,2977660,206209,13,1,12,7,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,snacks,both,Low-range product
32434210,2977660,206209,13,1,12,7,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,snacks,both,Low-range product
32434211,2977660,206209,13,1,12,7,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,snacks,both,Low-range product

In [121]:
# Count the number of orders for each weekday
weekday_counts = ords_prods_deps_cleaned['order_weekday'].value_counts()

# Identify the busiest and least busy days
busiest_day = weekday_counts.idxmax()  # The day with the highest orders
least_busy_day = weekday_counts.idxmin()  # The day with the lowest orders

# Assign categories
ords_prods_deps_cleaned['busiest_day'] = ords_prods_deps_cleaned['order_weekday'].apply(
    lambda x: 'Busiest day' if x == busiest_day else ('Least busy day' if x == least_busy_day else 'Regular day')
)

#Frequency in %
price_range_percentages = ords_prods_deps_cleaned['busiest_day'].value_counts(normalize=True) * 100
print(price_range_percentages)

# Display the first few rows to check the new column
print(ords_prods_deps_cleaned[['order_weekday', 'busiest_day']].head())

busiest_day
Regular day       69.178147
Busiest day       19.145315
Least busy day    11.676538
Name: proportion, dtype: float64
   order_weekday  busiest_day
0              2  Regular day
1              2  Regular day
2              2  Regular day
3              2  Regular day
4              2  Regular day

In [69]:
# Display data frame
ords_prods_deps_cleaned

,order_id,user_id,order_number,order_weekday,order_hour,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,final_merge_indicator,price_range,busiest_day
0,2539329,1,1,2,8,0,196,1,0,Soda,77,7,9.0,beverages,both,Mid-range product,Regular day
1,2539329,1,1,2,8,0,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,dairy eggs,both,Mid-range product,Regular day
2,2539329,1,1,2,8,0,12427,3,0,Original Beef Jerky,23,19,4.4,snacks,both,Low-range product,Regular day
3,2539329,1,1,2,8,0,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,snacks,both,Low-range product,Regular day
4,2539329,1,1,2,8,0,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,household,both,Low-range product,Regular day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,2977660,206209,13,1,12,7,14197,5,1,Tomato Paste,9,9,5.6,dry goods pasta,both,Mid-range product,Regular day
32434208,2977660,206209,13,1,12,7,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,snacks,both,Mid-range product,Regular day
32434209,2977660,206209,13,1,12,7,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,snacks,both,Low-range product,Regular day
32434210,2977660,206209,13,1,12,7,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,snacks,both,Low-range product,Regular day
32434211,2977660,206209,13,1,12,7,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,snacks,both,Low-range product,Regular day

#### Count the number of orders for each weekday
weekday_order_counts = ords_prods_deps_cleaned['order_weekday'].value_counts(dropna = False)

#### Find the busiest weekday by identifying the weekday with the maximum number of orders
busiest_weekday = weekday_order_counts.idxmax()
busiest_count = weekday_order_counts.max()
least_busiest_weekday = weekday_order_counts.idxmin()
least_busiest_count = weekday_order_counts.min()

#### Create a "busiest_day" column

result = []

for value in ords_prods_deps_cleaned['weekday_order_counts']:
  if value == 0:
    result.append('Busiest day')
  elif value == 4:
    result.append('Least busy')
  else:
    result.append('Regularly busy')

#### Display the result
print(f"The busiest weekday is {busiest_weekday} with {busiest_count} orders.")
print(f"The least busiest weekday is {least_busiest_weekday} with {least_busiest_count} orders.")

#### Create a "busiest_day" column

result = []

for value in ords_prods_deps_cleaned['weekday_order_counts']:
  if value == 0:
    result.append('Busiest day')
  elif value == 4:
    result.append('Least busy')
  else:
    result.append('Regularly busy')

#### Create a mapping of the busiest and least busy days
busiest_weekday = weekday_order_counts.idxmax()
least_busiest_weekday = weekday_order_counts.idxmin()

#### Create a new column 'busiest_day' to classify the days
def classify_day(weekday):
if weekday == busiest_weekday:
return 'Busiest day'
elif weekday == least_busiest_weekday:
return 'Least busy'
else:
return 'Regularly busy'

#### Apply the function to create the 'busiest_day' column
ords_prods_deps_cleaned['busiest_day'] = ords_prods_deps_cleaned['order_weekday'].apply(classify_day)

#### Display a snippet of the updated DataFrame
print(ords_prods_deps_cleaned.head())

#### Create a mapping of the busiest and least busy days
busiest_weekday = weekday_order_counts.idxmax()
least_busiest_weekday = weekday_order_counts.idxmin()

#### Create a new column 'busiest_day' to classify the days using a lambda function
ords_prods_deps_cleaned['busiest_day'] = ords_prods_deps_cleaned['order_weekday'].apply(
lambda weekday: 'Busiest day' if weekday == busiest_weekday else
'Least busy' if weekday == least_busiest_weekday else
'Regularly busy'
)

#### Display head of updated DataFrame
ords_prods_deps_cleaned.head()

#### Display counts for busy-ness categories

ords_prods_deps_cleaned['busiest_day'].value_counts(dropna = False)

## 3.3 Change “Busiest day” to become “Busiest days” (plural) for the two busiest days of the week as opposed to the single busiest day.

In [123]:
# Count the number of orders for each weekday
weekday_counts = ords_prods_deps_cleaned['order_weekday'].value_counts()

# Identify the top 2 busiest days
busiest_days = weekday_counts.nlargest(2).index.tolist()  # Get the top 2 busiest days
least_busy_day = weekday_counts.idxmin()  # Get the least busy day

# Assign categories
ords_prods_deps_cleaned['busiest_days'] = ords_prods_deps_cleaned['order_weekday'].apply(
    lambda x: 'Busiest days' if x in busiest_days else ('Least busy day' if x == least_busy_day else 'Regular day')
)

#Frequency in %
price_range_percentages = ords_prods_deps_cleaned['busiest_days'].value_counts(normalize=True) * 100
print(price_range_percentages)

# Display the first few rows to check the new column
print(ords_prods_deps_cleaned[['order_weekday', 'busiest_days']].head())

busiest_days
Regular day       51.709463
Busiest days      36.613999
Least busy day    11.676538
Name: proportion, dtype: float64
   order_weekday busiest_days
0              2  Regular day
1              2  Regular day
2              2  Regular day
3              2  Regular day
4              2  Regular day

# Find the two busiest weekdays
top_two_busiest_weekdays = weekday_order_counts.nlargest(2).index

# Create a new column 'busiest_days' to classify the days using a lambda function
ords_prods_deps_cleaned['busiest_days'] = ords_prods_deps_cleaned['order_weekday'].apply(
lambda weekday: 'Busiest days' if weekday in top_two_busiest_weekdays else
'Least busy' if weekday == least_busiest_weekday else
'Regularly busy'
)

# Display head of updated DataFrame
ords_prods_deps_cleaned.head()

### 3.4 Create a column for the two slowest days

In [125]:
# Count the number of orders for each weekday
weekday_counts = ords_prods_deps_cleaned['order_weekday'].value_counts()

# Identify the two slowest days
slowest_days = weekday_counts.nsmallest(2).index.tolist()  # Get the bottom 2 slowest days
busiest_day = weekday_counts.idxmax()  # Get the single busiest day

# Assign categories
ords_prods_deps_cleaned['slowest_days'] = ords_prods_deps_cleaned['order_weekday'].apply(
    lambda x: 'Slowest days' if x in slowest_days else ('Busiest day' if x == busiest_day else 'Regular day')
)

#Frequency in %
price_range_percentages = ords_prods_deps_cleaned['slowest_days'].value_counts(normalize=True) * 100
print(price_range_percentages)

# Display the first few rows to check the new column
print(ords_prods_deps_cleaned[['order_weekday', 'slowest_days']].head())

slowest_days
Regular day     57.326168
Slowest days    23.528517
Busiest day     19.145315
Name: proportion, dtype: float64
   order_weekday slowest_days
0              2  Regular day
1              2  Regular day
2              2  Regular day
3              2  Regular day
4              2  Regular day

#### Find the two slowest weekdays
two_slowest_weekdays = weekday_order_counts.nsmallest(2).index

#### Add a new column 'slowest_days' to classify the two slowest days
ords_prods_deps_cleaned['slowest_days'] = ords_prods_deps_cleaned['order_weekday'].apply(
lambda weekday: 'Slowest days' if weekday in two_slowest_weekdays else 'Not slowest'
)

#### Display head of updated DataFrame
ords_prods_deps_cleaned.head()

In [75]:
# Display counts for busy-ness categories

ords_prods_deps_cleaned['busiest_day'].value_counts(dropna = False)

busiest_day
Regular day       22437387
Busiest day        6209632
Least busy day     3787193
Name: count, dtype: int64

#### Print the busiest weekday from weekday_order_counts
print(weekday_order_counts.nlargest(1))

In [ ]:
# the count is correct

In [79]:
# Display counts for busy-ness categories

ords_prods_deps_cleaned['busiest_days'].value_counts(dropna = False)

busiest_days
Regular day       16771557
Busiest days      11875462
Least busy day     3787193
Name: count, dtype: int64

#### Print the top2 busiest weekdays from weekday_order_counts
print(weekday_order_counts.nlargest(2))

In [ ]:
# the count seems correct

In [81]:
# Display counts for busy-ness categories

ords_prods_deps_cleaned['slowest_days'].value_counts(dropna = False)

slowest_days
Regular day     18593291
Slowest days     7631289
Busiest day      6209632
Name: count, dtype: int64

#### Print the slowest weekdays from weekday_order_counts
print(weekday_order_counts.nsmallest(2))

In [ ]:
# the count seems correct

# 4. Identify the busiest hours of the day

In [ ]:
# Rather than by hour label periods of time: “Most orders,” “Average orders,” and “Fewest orders.” 
# Create a new column containing these labels called “busiest_period_of_day.”

In [127]:
# Count the number of orders for each hour
hourly_counts = ords_prods_deps_cleaned['order_hour'].value_counts().sort_index()

# Calculate quartiles
q1 = hourly_counts.quantile(0.25)  # Bottom 25% threshold
q3 = hourly_counts.quantile(0.75)  # Upper 25% threshold

# Assign categories based on quartiles
ords_prods_deps_cleaned['busiest_period_of_day'] = ords_prods_deps_cleaned['order_hour'].apply(
    lambda x: 'Most orders' if hourly_counts[x] >= q3 else 
              ('Fewest orders' if hourly_counts[x] <= q1 else 'Average orders')
)

#Frequency in %
price_range_percentages = ords_prods_deps_cleaned['busiest_period_of_day'].value_counts(normalize=True) * 100
print(price_range_percentages)

# Display first few rows to check the new column
print(ords_prods_deps_cleaned[['order_hour', 'busiest_period_of_day']].head())

busiest_period_of_day
Most orders       49.771926
Average orders    48.387992
Fewest orders      1.840082
Name: proportion, dtype: float64
   order_hour busiest_period_of_day
0           8        Average orders
1           8        Average orders
2           8        Average orders
3           8        Average orders
4           8        Average orders

#### Calculate the number of orders for each hour
hourly_order_counts = ords_prods_deps_cleaned['order_hour'].value_counts()

#### Determine the busiest hour and the least busy hour
most_order_hour = hourly_order_counts.idxmax()
fewest_order_hour = hourly_order_counts.idxmin()

#### Alternatively, quantiles can define thresholds for categorizing 'Average orders'
upper_threshold = hourly_order_counts.quantile(0.75) # Upper 25% for "Most orders"
lower_threshold = hourly_order_counts.quantile(0.25) # Lower 25% for "Fewest orders"

#### Create the 'order_time_of_day' column
ords_prods_deps_cleaned['order_time_of_day'] = ords_prods_deps_cleaned['order_hour'].apply(
lambda hour: 'Most orders' if hourly_order_counts[hour] >= upper_threshold else
'Fewest orders' if hourly_order_counts[hour] <= lower_threshold else
'Average orders'
)

#### Display a snippet of the updated DataFrame to verify
print(ords_prods_deps_cleaned[['order_hour', 'order_time_of_day']].drop_duplicates().sort_values(by='order_hour'))

#### Print the frequency of each category in the 'order_time_of_day' column
order_time_of_day_counts = ords_prods_deps_cleaned['order_time_of_day'].value_counts()

print(order_time_of_day_counts)

In [91]:
# Display data frame
ords_prods_deps_cleaned

,order_id,user_id,order_number,order_weekday,order_hour,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,department,final_merge_indicator,price_range,busiest_day,busiest_days,slowest_days,order_time_of_day,busiest_period_of_day
0,2539329,1,1,2,8,0,196,1,0,Soda,...,7,9.0,beverages,both,Mid-range product,Regular day,Regular day,Regular day,Average orders,Average orders
1,2539329,1,1,2,8,0,14084,2,0,Organic Unsweetened Vanilla Almond Milk,...,16,12.5,dairy eggs,both,Mid-range product,Regular day,Regular day,Regular day,Average orders,Average orders
2,2539329,1,1,2,8,0,12427,3,0,Original Beef Jerky,...,19,4.4,snacks,both,Low-range product,Regular day,Regular day,Regular day,Average orders,Average orders
3,2539329,1,1,2,8,0,26088,4,0,Aged White Cheddar Popcorn,...,19,4.7,snacks,both,Low-range product,Regular day,Regular day,Regular day,Average orders,Average orders
4,2539329,1,1,2,8,0,26405,5,0,XL Pick-A-Size Paper Towel Rolls,...,17,1.0,household,both,Low-range product,Regular day,Regular day,Regular day,Average orders,Average orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,2977660,206209,13,1,12,7,14197,5,1,Tomato Paste,...,9,5.6,dry goods pasta,both,Mid-range product,Regular day,Busiest days,Regular day,Most orders,Most orders
32434208,2977660,206209,13,1,12,7,38730,6,0,Brownie Crunch High Protein Bar,...,19,5.9,snacks,both,Mid-range product,Regular day,Busiest days,Regular day,Most orders,Most orders
32434209,2977660,206209,13,1,12,7,31477,7,0,High Protein Bar Chunky Peanut Butter,...,19,4.2,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders,Most orders
32434210,2977660,206209,13,1,12,7,6567,8,0,Chocolate Peanut Butter Protein Bar,...,19,4.9,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders,Most orders
32434211,2977660,206209,13,1,12,7,22920,9,0,Roasted & Salted Shelled Pistachios,...,19,1.7,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders,Most orders

In [93]:
ords_prods_deps_cleaned.drop(columns = ['order_time_of_day'])

,order_id,user_id,order_number,order_weekday,order_hour,days_since_last_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,final_merge_indicator,price_range,busiest_day,busiest_days,slowest_days,busiest_period_of_day
0,2539329,1,1,2,8,0,196,1,0,Soda,77,7,9.0,beverages,both,Mid-range product,Regular day,Regular day,Regular day,Average orders
1,2539329,1,1,2,8,0,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,dairy eggs,both,Mid-range product,Regular day,Regular day,Regular day,Average orders
2,2539329,1,1,2,8,0,12427,3,0,Original Beef Jerky,23,19,4.4,snacks,both,Low-range product,Regular day,Regular day,Regular day,Average orders
3,2539329,1,1,2,8,0,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,snacks,both,Low-range product,Regular day,Regular day,Regular day,Average orders
4,2539329,1,1,2,8,0,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,household,both,Low-range product,Regular day,Regular day,Regular day,Average orders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32434207,2977660,206209,13,1,12,7,14197,5,1,Tomato Paste,9,9,5.6,dry goods pasta,both,Mid-range product,Regular day,Busiest days,Regular day,Most orders
32434208,2977660,206209,13,1,12,7,38730,6,0,Brownie Crunch High Protein Bar,3,19,5.9,snacks,both,Mid-range product,Regular day,Busiest days,Regular day,Most orders
32434209,2977660,206209,13,1,12,7,31477,7,0,High Protein Bar Chunky Peanut Butter,3,19,4.2,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders
32434210,2977660,206209,13,1,12,7,6567,8,0,Chocolate Peanut Butter Protein Bar,3,19,4.9,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders
32434211,2977660,206209,13,1,12,7,22920,9,0,Roasted & Salted Shelled Pistachios,117,19,1.7,snacks,both,Low-range product,Regular day,Busiest days,Regular day,Most orders

# 5. Exporting Data

In [95]:
# Export ords_prods_deps_cleaned pickle
ords_prods_deps_cleaned.to_pickle(os.path.join('/Users', 'xxx', 'Documents', 'Instacart Basket Analysis - 2025-01-05', '02 - Data','Prepared Data', 'ords_prods_deps_cleaned_expanded.pkl'))